### ISSUE TITLE
socket.error : timed out

### ISSUE THREAD

**Issue by JAbelP** [adamkempenich/magichome-python#8]
I continue to get the socket.error when trying to do anything with the bulb

import MagicHomeApi

bulb = MagicHomeApi.MagicHomeApi('xx.xx.x.xxx',2)

bulb.get_status()

Establishing connection with the device.
Caught exception socket.error : timed out
Traceback (most recent call last):
  File "c:\Users\User\Documents\Code\Python\MagicHome\DemoBulb", line 6, in <module>
Caught exception socket.error : [Errno 9] Bad file descriptor
    bulb.get_status()
  File "c:\Users\User\Documents\Code\Python\MagicHome\MagicHomeApi.py", line 50, in get_status
    return self.s.recv(15)
  File "C:\Python27\lib\socket.py", line 174, in _dummy
    raise error(EBADF, 'Bad file descriptor')
socket.error: [Errno 9] Bad file descriptor

**Comment by JAbelP** [comment]
I think I had it on a wifi connection that doesn't work I will try after work
